"use client";

import { motion } from "framer-motion";
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Brain, CheckCircle2, ChevronRight, Gauge, GitBranch, Layers3, LineChart, Radar, ShieldCheck, Sparkles, Target, Zap } from "lucide-react";
import { CXTimeSeries, JourneyBars, JourneyRadar, PriorityMatrix, ScenarioChart, SentimentTrend, TinySpark } from "@/components/charts";
import { cxHistory, insights, initiatives, journeys, kpis, painPoints, recommendations, rootCauses, segmentChannels } from "@/content/cx-data";
import { formatDelta } from "@/lib/utils";

const iconMap = [Gauge, LineChart, ShieldCheck, Activity, AlertTriangle, Radar, GitBranch, Zap];
const sparks = [[66, 69, 71, 70, 74], [31, 33, 29, 36, 42], [76, 78, 81, 82, 83], [88, 89, 90, 91, 92], [10, 9, 8, 7, 6.8], [4.08, 4.12, 4.42, 4.36, 4.34], [142, 136, 111, 125, 133], [11, 9.8, 8.2, 7.9, 7.4]];

function SectionTitle({ eyebrow, title, sub }: { eyebrow: string; title: string; sub?: string }) {
  return <div className="mb-6 flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-teal-300 md:text-teal-600">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight text-slate-950 md:text-4xl">{title}</h2></div>{sub && <p className="max-w-xl text-sm leading-6 text-slate-500">{sub}</p>}</div>;
}

function DarkSectionTitle({ eyebrow, title }: { eyebrow: string; title: string }) {
  return <div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-teal-300">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight text-white md:text-4xl">{title}</h2></div>;
}

export function DashboardShell() {
  return <main className="min-h-screen overflow-hidden"><div className="dashboard-grid pointer-events-none fixed inset-0 opacity-70" />
    <header className="relative mx-auto flex max-w-7xl items-center justify-between px-4 py-5 md:px-8"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl border border-white/10 bg-white/10"><Brain className="h-5 w-5 text-teal-300" /></div><div><p className="text-sm font-semibold">Голос клиента и CX</p><p className="text-xs text-slate-400">Executive Command Center</p></div></div><div className="hidden items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-2 text-xs text-slate-300 md:flex"><span className="h-2 w-2 rounded-full bg-teal-300"/> Synthetic enterprise dataset · updated 08:30</div></header>

    <section className="relative mx-auto max-w-7xl px-4 pb-14 pt-6 md:px-8 md:pb-20"><div className="mb-7 grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.55}}><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-teal-300/20 bg-teal-300/10 px-3 py-1.5 text-xs font-medium text-teal-100"><Sparkles className="h-3.5 w-3.5"/> Signal density cockpit for board decisions</div><h1 className="max-w-4xl text-4xl font-semibold tracking-[-0.06em] text-white md:text-6xl">CX банка сейчас: <span className="text-teal-200">стабильно улучшается</span>, но onboarding и support создают churn risk.</h1><div className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4"><div className="card rounded-3xl p-4"><p className="text-xs text-slate-400">Health</p><p className="metric-tabular mt-1 text-4xl font-semibold">74</p><p className="text-xs text-teal-300">+5 QoQ</p></div><div className="card rounded-3xl p-4"><p className="text-xs text-slate-400">NPS</p><p className="metric-tabular mt-1 text-4xl font-semibold">42</p><p className="text-xs text-teal-300">+8 YoY</p></div><div className="card rounded-3xl p-4"><p className="text-xs text-slate-400">Top risk</p><p className="mt-1 text-xl font-semibold">KYC latency</p><p className="text-xs text-rose-300">-5.8 NPS</p></div><div className="card rounded-3xl p-4"><p className="text-xs text-slate-400">Next action</p><p className="mt-1 text-xl font-semibold">Support &lt;5m</p><p className="text-xs text-teal-300">+11 NPS</p></div></div></motion.div><motion.div initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}} transition={{duration:.6,delay:.1}} className="card rounded-[2rem] p-4"><div className="mb-4 flex items-center justify-between"><p className="text-sm font-medium text-slate-200">Executive overview</p><p className="text-xs text-slate-400">Confidence 94%</p></div><div className="grid grid-cols-2 gap-3">{kpis.map((k, i) => { const Icon = iconMap[i]; return <div key={k.label} className="rounded-2xl border border-white/10 bg-white/[.035] p-3"><div className="flex items-center justify-between"><Icon className="h-4 w-4 text-slate-400"/><span className={k.tone === "bad" ? "text-rose-300" : k.tone === "risk" ? "text-amber-300" : "text-teal-300"}>{formatDelta(k.delta as number)} {k.hint}</span></div><p className="mt-3 text-xs text-slate-400">{k.label}</p><p className="metric-tabular text-2xl font-semibold">{k.value}<span className="text-sm text-slate-400">{k.suffix}</span></p><TinySpark data={sparks[i]} color={k.tone === "bad" ? "#fb7185" : k.tone === "risk" ? "#f59e0b" : "#2dd4bf"}/></div>})}</div></motion.div></div>
      <div className="grid gap-4 md:grid-cols-3"><div className="card rounded-3xl p-5 md:col-span-2"><DarkSectionTitle eyebrow="CX over time" title="NPS восстанавливается после Q3; complaints снова растут в May."/><CXTimeSeries /></div><div className="card rounded-3xl p-5"><DarkSectionTitle eyebrow="Voice of customer" title="Top pain points"/>{painPoints.map(p => <div key={p.issue} className="mb-3 rounded-2xl border border-white/10 bg-white/[.035] p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium">{p.issue}</p><span className={p.change > 0 ? "text-rose-300" : "text-teal-300"}>{p.change > 0 ? "+" : ""}{p.change}%</span></div><div className="mt-2 h-1.5 rounded-full bg-white/10"><div className="h-1.5 rounded-full bg-gradient-to-r from-teal-300 to-rose-400" style={{width:`${p.risk}%`}}/></div><p className="mt-2 text-xs text-slate-400">{p.volume.toLocaleString("ru-RU")} signals · {p.impact}</p></div>)}</div></div>
    </section>

    <section className="relative bg-slate-50 px-4 py-14 md:px-8 md:py-20"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Customer journeys" title="Где CX ломается" sub="Journey health combines satisfaction, drop-off, pain level, resolution success and customer effort."/><div className="grid gap-5 lg:grid-cols-[.95fr_1.05fr]"><div className="light-card rounded-[2rem] p-5"><JourneyRadar /></div><div className="light-card rounded-[2rem] p-5"><JourneyBars /></div></div><div className="mt-5 grid gap-3 md:grid-cols-3">{journeys.slice(0,9).map(j => <div key={j.name} className="light-card rounded-3xl p-4"><div className="flex items-center justify-between"><p className="font-semibold text-slate-900">{j.name}</p><span className={j.trend < 0 ? "text-rose-600" : "text-teal-700"}>{j.trend > 0 ? <ArrowUpRight className="h-4 w-4"/> : <ArrowDownRight className="h-4 w-4"/>}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs text-slate-500"><span>Sat <b className="block text-lg text-slate-950">{j.sat}</b></span><span>Pain <b className="block text-lg text-slate-950">{j.pain}</b></span><span>Effort <b className="block text-lg text-slate-950">{j.effort}</b></span></div></div>)}</div></div></section>

    <section className="relative bg-slate-50 px-4 pb-14 md:px-8 md:pb-20"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[1.08fr_.92fr]"><div><SectionTitle eyebrow="Root cause analytics" title="Почему ухудшается CX"/><div className="space-y-3">{rootCauses.map((r, i) => <div key={r.cause} className="light-card rounded-3xl p-4"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-2xl bg-slate-950 text-sm text-white">{i+1}</span><div><p className="font-semibold text-slate-950">{r.cause}</p><p className="text-xs text-slate-500">{r.chain}</p></div></div><div className="text-right"><p className="metric-tabular text-xl font-semibold text-slate-950">{r.impact}</p><p className="text-xs text-slate-500">impact pts · {r.confidence}% conf.</p></div></div></div>)}</div></div><div><SectionTitle eyebrow="What improved CX" title="Что сработало"/><div className="space-y-3">{initiatives.map(i => <div key={i.name} className="light-card rounded-3xl p-4"><div className="flex items-start justify-between"><div><p className="font-semibold text-slate-950">{i.name}</p><p className="text-xs text-slate-500">{i.status} · ROI {i.roi}</p></div><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-medium text-teal-700">{i.impact}</span></div><div className="mt-3 flex items-center gap-3 text-xs text-slate-500"><span>{i.before}</span><div className="h-1.5 flex-1 rounded-full bg-slate-200"><div className="h-1.5 rounded-full bg-teal-500" style={{width:`${i.after}%`}}/></div><span>{i.after}</span></div></div>)}</div></div></div></section>

    <section className="relative bg-white px-4 py-14 md:px-8 md:py-20"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="What to do next" title="Executive recommendations engine" sub="Prioritized by expected CX impact, urgency, business value and implementation complexity."/><div className="grid gap-5 lg:grid-cols-[.92fr_1.08fr]"><div className="light-card rounded-[2rem] p-5"><PriorityMatrix /></div><div className="grid gap-3">{recommendations.map(r => <div key={r.action} className="light-card rounded-3xl p-4"><div className="flex items-center justify-between gap-4"><div><p className="font-semibold text-slate-950">{r.action}</p><p className="text-xs text-slate-500">Business value: {r.value}</p></div><div className="text-right"><p className="text-xl font-semibold text-teal-700">{r.impact}</p><p className="text-xs text-slate-500">urgency {r.urgency}</p></div></div></div>)}</div></div></div></section>

    <section className="relative bg-slate-950 px-4 py-14 md:px-8 md:py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-5 lg:grid-cols-3"><div className="lg:col-span-2"><DarkSectionTitle eyebrow="Segments / channels" title="Где CX хуже по клиентам и каналам"/><div className="grid gap-3 md:grid-cols-2">{segmentChannels.map(s => <div key={s.name} className="card rounded-3xl p-4"><div className="flex items-center justify-between"><p className="font-semibold">{s.name}</p><span className={s.risk > 55 ? "text-rose-300" : "text-teal-300"}>risk {s.risk}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-400"><span>NPS <b className="block text-2xl text-white">{s.nps}</b></span><span>CSI <b className="block text-2xl text-white">{s.csi}%</b></span></div></div>)}</div></div><div className="card rounded-[2rem] p-5"><DarkSectionTitle eyebrow="Executive insights" title="5 signals for board"/><div className="space-y-3">{insights.map(x => <div key={x} className="flex gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-teal-300"/><p className="text-sm leading-5 text-slate-200">{x}</p></div>)}</div></div></div><div className="mt-5 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="card rounded-[2rem] p-5"><DarkSectionTitle eyebrow="Sentiment evolution" title="Digital signals vs churn risk"/><SentimentTrend /></div><div className="rounded-[2rem] border border-white/10 bg-white p-5 text-slate-950"><SectionTitle eyebrow="Future CX scenarios" title="What happens if…"/><ScenarioChart /></div></div></div></section>

    <footer className="bg-slate-950 px-4 pb-8 text-center text-xs text-slate-500 md:px-8">Synthetic data · banking CX intelligence model · no secrets stored · built for executive 30–90 sec readout</footer>
  </main>;
}
